sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - CS_CHECK=true
    - php: 5.6
    - php: 7
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
  - phpenv config-rm xdebug.ini || return 0
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction

script:
  - composer test
  - if [[ $CS_CHECK == 'true' ]]; then composer cs ; fi
